# disable python warnings if they annoy you
ignore_warnings: False

# ask user for tags if none are provided in the config
enforce_tags: True

# pretty print config tree at the start of the run using Rich library
print_config: True

# Huggingface API of Biomedclip for pretrained model and tokenizer
biomedclip_hf_api: hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224

# Huggingface API of PubMedBERT for pretrained model and tokenizer
pubmedbert_hf_api: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext

# Huggingface API of CLIPSeg for pretrained model and tokenizer
clipseg_hf_api: CIDAS/clipseg-rd64-refined