_target_: src.models.BaseModule
net:
  _target_: src.models.CLIPSeg
  clipseg_hf_api: ${extras.clipseg_hf_api}
  freeze_encoder: false
  freeze_decoder: false

loss_fn: 
  _target_: monai.losses.DiceCELoss
  lambda_dice: 1.5
  lambda_ce: 1.0
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.001
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  factor: 0.3
  patience: 5