_target_: src.models.BaseModule
net:
  _target_: src.models.CLIPSegAdapter
  clipseg_hf_api: ${extras.clipseg_hf_api}
  adapter_dim: 512
  freeze_clipseg: true
  adapter_in_v: true
  adapter_in_l: true
  adapter_in_cond: true

loss_fn: 
  _target_: monai.losses.DiceCELoss
  lambda_dice: 1.0
  lambda_ce: 0.2
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 2.0e-3
  weight_decay: 0.001
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  factor: 0.1
  patience: 5