_target_: src.models.BaseModule
net:
  _target_: src.models.CLIPSegCoOp
  clipseg_hf_api: ${extras.clipseg_hf_api}
  n_ctx: 300
  ctx_init: ""
  freeze_encoder: true
  freeze_decoder: true

loss_fn: 
  _target_: monai.losses.DiceCELoss
  lambda_dice: 1.5
  lambda_ce: 1.0
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 2.0e-3
  weight_decay: 0.001
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  eta_min: 0.0001
  T_max: 50